sudo: false
language: c
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

matrix:
    include:

        # Linux, Python 2.7
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.10
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.11
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.12
        - os: linux
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.13

        # Linux, Python 3.4
        - os: linux
          env: PYTHON_VERSION=3.4 NUMPY_VERSION=1.11

        # Linux, Python 3.5
        - os: linux
          env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.12

        # Linux, Python 3.6
        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.13

        # OSX
        - os: osx
          env: PYTHON_VERSION=2.7 NUMPY_VERSION=1.13
        - os: osx
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.13

install:
    - source .ci/travis.sh

script:
    - py.test -v tests
